### ISSUE TITLE
setModel doesn't appear to correctly rebind events

### ISSUE THREAD

**Issue by pkmitre** [walmartlabs/thorax#283]
When calling setModel on a view that defines model event handlers via the events hash, the event handlers don't appear to be correctly re-attached to the new model. This appears to work as expected in 2.0.0rc6 (in the example below, shows the change to model m2 on the console), but not in 2.0.1 and later (doesn't log anything at all to the console):

    class MyView extends Thorax.View
      template: Handlebars.compile '{{title}}'
      events:
        model:
          change: (model) -> console.log "CHANGED: ", model.changed

    m1 = new Thorax.Model(title: 'M1')
    m2 = new Thorax.Model(title: 'M2')

    view = new MyView(model: m1)
    view.appendTo 'body'

    view.setModel m2

    m1.set title: 'M1 TWEAKED'
    m2.set title: 'M2 TWEAKED'

Fiddle showing expected behavior in 2.0.0rc6: http://jsfiddle.net/KRuPZ/57/

There's a slightly different result if setModel is called within the view's initialize method; again it works as expected in 2.0.0rc6 (shows the change to model m4), but not in 2.0.1 and later (actually shows the change to model m3):

    class MyView2 extends Thorax.View
      template: Handlebars.compile '{{title}}'
      events:
        model:
          change: (model) -> console.log "CHANGED: ", model.changed
      initialize: ->
        @setModel @otherModel

    m3 = new Thorax.Model(title: 'M3')
    m4 = new Thorax.Model(title: 'M4')

    view = new MyView2(model: m3, otherModel: m4)
    view.appendTo 'body'

    m3.set title: 'M3 TWEAKED'
    m4.set title: 'M4 TWEAKED'

Again, a fiddle showing expected behavior in 2.0.0rc6: http://jsfiddle.net/5Khz9/1/

**Comment by kpdecker** [comment]
Thanks for figuring this out @liorch88. Fix will be in the next release.
