### ISSUE TITLE
Can't render optional heading in collection properly

### ISSUE THREAD

**Issue by mindhaq** [walmartlabs/thorax#284]
I have a collection where each item has a date (among others), which is sorted by that date already. I want to render the whole collection in a way that whenever the first item of a particular day is being rendered, that day will be rendered before the item.

The expected output should look like this:
```
<ul>
  <li>Monday</li>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Tuesday</li>
  <li>Item 3</li>
  <li>...</li>
</ul>
```

The itemModel already has a working property ```firstOfDay```.

My template looks like this:
```
{{#collection tag="ul"}}
  {{#if firstOfDay}}
    <li>{{formatDate date}}</li>
  {{/if}}

  <li>
    ... (render item data)
  </li>
{{/collection}}
```

However, Thorax now renders another ```<li>``` around my complete item template:
```
<ul>
  <li data-view-name=""... >
    <li>Monday</li>
    <li>Item 1</li>
  </li>
  <li data-view-name=""... >
    <li>Item 2</li>
  </li>
  <li data-view-name=""... >
    <li>Tuesday</li>
    <li>Item 3</li>
  </li>
  <li data-view-name=""... >
    <li>...</li>
  </li>
</ul>
```

This results in illegal HTML (li must be inside ul), and makes it much harder to style a list like this.

I guess the same problem would be there if you'd like to add a table header in a long table every 20 rows or so.

Specifying an empty itemTag results in no rendering at all.

I'd like to have a way where I have more control over item rendering, specify a prefix to it or so.

**Comment by kpdecker** [comment]
I can't seem to reproduce with a simple test case. Glad to reopen if someone posts a test case or fiddle that demonstrates the issue.

```
  it('should support multiple list items in a single item view', function() {
    var collection = new Thorax.Collection(letterCollection.models);
    var view = new Thorax.View({
      collection: collection,
      template: Handlebars.compile('{{#collection tag="ul"}} <li>{{letter}}</li> <li>{{letter}}</li> {{/collection}}')
    });
    view.render();
    console.log(view.html());
    expect(view.$('li').length).to.equal(collection.length);
    expect(view.$('li').eq(0).html()).to.equal('a');
  });
```

```
<ul data-view-cid="view11" data-view-helper="collection" data-view-helper-restore="collection" data-collection-element="true" data-collection-cid="collection7" class=""><li data-model-cid="c3">a</li><li data-model-cid="c3">a</li><li data-model-cid="c4">b</li><li data-model-cid="c4">b</li><li data-model-cid="c5">c</li><li data-model-cid="c5">c</li><li data-model-cid="c6">d</li><li data-model-cid="c6">d</li></ul>
```
