### ISSUE TITLE
ChildView of ItemView in CollectionView is causing problems.. 

### ISSUE THREAD

**Issue by wouterwisselink** [walmartlabs/thorax#301]
This problem is a bit hard to explain, but I'll give it a try. When I'm using a nested view inside an ItemView of a CollectionView the next ItemView will append inside the previous childView.
```html
<div id="items">
    {{#collection}}
        <div class="item">
            {{title}}
            {{view childView}}
        </div>
    {{/collection}}
</div>
```

Results in:
```html
<div id="items">
    <div class="item">
         The title
         <div class="childView">
              This is the childView..

               <div class="item">
                   The title
                   <div class="childView">
                         This is the childView..
                   </div>
               </div>
               // And so on...
         </div>
    </div>
</div>
```
It looks like the collectionView is keeping a reference to the last view there was something inserted into. So in this case the childView of the itemView, but it should be the itemView. 

I hope I made myself a bit clear, because it is frustrating.

**Comment by kpdecker** [comment]
Closing this but glad to reopen with a repo case.
