### ISSUE TITLE
CollectionView itemFilter erroneously shows child views that have the same model

### ISSUE THREAD

**Issue by jasonwebster** [walmartlabs/thorax#306]
If the itemView has child views that use the same model, they are shown when the filter is applied, even though the intent is obviously just to show or hide the itemView itself.

Offending line: https://github.com/walmartlabs/thorax/blob/master/src/collection.js#L385

Offending code:
```js
function applyItemVisiblityFilter(model) {
  var $el = this.getCollectionElement();
  this.itemFilter && $el.find('[' + modelCidAttributeName + '="' + model.cid + '"]')[itemShouldBeVisible.call(this, model) ? 'show' : 'hide']();
}
```

I'll submit a patch, just logging the issue.

**Comment by kpdecker** [comment]
Ages later: I have a fix for this, but it's quite a bit more expensive. Do you remember what the use case was that led to you finding this behavior?

**Comment by kpdecker** [comment]
When ahead and merged this hopefully it's not too much more expensive in the simple case since the closest call will only walk up 1 level.

**Comment by jasonwebster** [comment]
> Do you remember what the use case was that led to you finding this behavior?

Oh boy, it's been a while, but I believe it was something like this:

I had an item view that had child views that used the same model as their parent (the item view). By default one of these child views was hidden--something that was supposed to be toggled by a UI control. When the itemFilter ran to filter the collection's item views, it would show all those child views, in all other item views.
