### ISSUE TITLE
CollectionView does not remove empty state if using collection.set() with multiple new models

### ISSUE THREAD

**Issue by jasonwebster** [walmartlabs/thorax#314]
Line in question: https://github.com/walmartlabs/thorax/blob/master/src/collection.js#L328

The handler on the CollectionView bound to the collections `add` event will only remove the empty state if the collection length equals exactly 1. When using Backbone's `set` on a collection, the `length` of the collection is updated to the new total _before_ the add events are fired.

**Comment by kpdecker** [comment]
This appears to be dependent on what version of backbone is being used. Under 1.1.0 there is a sort event that triggers the conversion from empty to not so this issue is not seen. Do we have any idea what Backbone versions this was filed against?

**Comment by kpdecker** [comment]
1.0.0 does the trick.

**Comment by kpdecker** [comment]
```
    it('should make non-empty after multiple insert', function() {
      var view = new Thorax.View({
        template: Handlebars.compile('{{#collection tag="ul"}}foo{{else}}bar{{/collection}}'),
        collection: new (Thorax.Collection.extend({url: false}))()
      });
      view.render();
      expect(view.$el.text()).to.equal('bar');
      view.collection.set([
        new Thorax.Model({id: 1, key: 'value'}),
        new Thorax.Model({id: 2, key: 'value'})
      ]);
      expect(view.$el.text()).to.equal('foofoo');
    });
```
