### ISSUE TITLE
Collection does not re render after a reset on IE

### ISSUE THREAD

**Issue by AzadMemon** [walmartlabs/thorax#381]
Currently, I'm using an AJAX request to fetch the entities of a collection, and then resetting the collection so that it only contains the new entities

<pre><code>
$.ajax({
     url: Application.Globals.apiURL + 'search',
     data: searchParameters,
     success: function(response, status, xhr) {
         var data = [],
             logdata;

         if (response.data && response.data.results) {
             view.params.total_results = response.data.total_results;
             data = response.data.results;
         } else if (response.data && response.data.recent) {
             view.params.total_results = response.data.total_results;
             data = response.data.recent;
         } else {
             view.params.total_results = 0;
             view.results.suggestions = response.similar;
         }

         if (!view.hasQuery()) {
             view.params.total_results = Math.min(view.params.total_results, 96);
         }

         if (view.collection) {
             view.collection.reset(data);
         }

         view.results.render();
     }
 });
</code></pre>

The collection is rendered on chrome and firefox, but on IE8 and IE11 (not sure of other IE versions cause I could only test on those 2), the collection doesn't render.

To make it work on IE8 and IE11, I added
<pre><code>view.results.renderCollection(); // IE fix
</code></pre>

after
<pre><code>
view.results.render();
</code></pre>

My attempt to track down where this failed using the developer tools on IE failed.

Any help would be greatly appreciated!

**Comment by kpdecker** [comment]
Closing this as I can't seem to reproduce on simple tests. If you post a jsbin/jsfiddle showing the failure then I'll be glad to reopen.
