### ISSUE TITLE
View properties inheritance

### ISSUE THREAD

**Issue by zverev** [walmartlabs/thorax#396]
Hi!

There is a collection view, that has child views with common properties, so I would like to inherit these properties from the parent view. I've read the docs and found, that child views have `parent` property, but I can't use it within `context` function. The same applies to `initialize` function.
Seems that this variable is declared after rendering a child view.
Here is an example of my problem: http://jsbin.com/givuxa/6/edit

How can I properly inherit view-related variables from parent view to put them in view context?

**Comment by kpdecker** [comment]
This was fixed in 3.0.0-alpha.5 by b8dd864ead1b73e90d2d5247cfbc4b7986c0832d. I'm working on getting a formal 3.0 release out to make this available.
