### ISSUE TITLE
url helper and pushState

### ISSUE THREAD

**Issue by bengladwell** [walmartlabs/thorax#399]
I submitted PR #398. It is admittedly a confused PR. I should have opened an issue first. I'll close the PR since I'm not even really suggesting that solution anymore.

Does the issue raised in the PR make sense?

I originally commented:
If you initialize Backbone.history with a root like "/path/" and pass a fragment like "/articles" to the url helper, you should get "/articles", not "/path/articles" [as a link href]. If you define a root, your route definitions do not include that root.

Later I realized that the root _should_ be included in the hrefs so that you get proper hrefs that can be rendered by the server. In my code, I am addressing this by overriding _anchorClick like this:
```javascript
  Thorax.View.prototype._anchorClick = function (event) {
    var target = $(event.currentTarget),
      href = target.attr('href');

    // Don't push if meta or shift key are clicked
    if (event.metaKey || event.shiftKey) {
      return true;
    }

    // Route anything that starts with # or / (excluding //domain urls)
    if (href && (href[0] === '#' || (href[0] === '/' && href[1] !== '/'))) {
      // everything about this _anchorClick should be the same as upstream except the following block
      if (Backbone.history.options.root.length > 1 && href.indexOf(Backbone.history.options.root) === 0) {
        href = '/' + href.substr(Backbone.history.options.root.length);
      }
      Backbone.history.navigate(href, {
        trigger: true
      });
      return false;
    }
    return true;
  };
```

This block:
```javascript
if (Backbone.history.options.root.length > 1 && href.indexOf(Backbone.history.options.root) === 0) {
  href = '/' + href.substr(Backbone.history.options.root.length);
}
```
strips out the root before navigating if the href begins with the root.

Does this seem like a reasonable solution?

**Comment by kpdecker** [comment]
This should hopefully be fixed in the next release.
