### ISSUE TITLE
Thorax Architecture Example Page 404

### ISSUE THREAD

**Issue by osiris43** [walmartlabs/thorax#406]
http://addyosmani.github.io/todomvc/labs/architecture-examples/thorax/

Trying to figure out why the thorax generator on my machine doesn't seem to work properly but can't find a working example to compare it too.

**Comment by kpdecker** [comment]
I think this has been moved to http://todomvc.com/examples/thorax/

Where did you find the link above?
What sort of failure are you seeing with the generator?

**Comment by osiris43** [comment]
It's on the Getting Started page.  None of the links in the TodoMVC section work.

When a new app is created with the generator, it runs both bower install and npm install.  For some reason on my machine (I haven't tested others), I was required to choose a particular version of jquery.  The first few times through, I picked the wrong one.  Once I figured that out, everything worked.

**Comment by kpdecker** [comment]
Ok. I'll work on getting the links updated.

Do you know what versions of jQuery were failing? What sort of failures
were you seeing?

**Comment by kpdecker** [comment]
The links have been updated. If you saw issues running Thorax under specific versions of jQuery, could you open a bug with that information and we'll be glad to take a look?
