### ISSUE TITLE
Mark as abandoned?

### ISSUE THREAD

**Issue by samccone** [walmartlabs/thorax#414]
via @eastridge's comment here https://github.com/tastejs/todomvc/issues/1110#issuecomment-80568088 Is it fair to say that this should be noted in the readme?

**Comment by eastridge** [comment]
I do not think @kpdecker will be updating the todomvc app, and I have ceased development on Thorax, but that is not the same as the framework itself being abandoned. Bug fixes and new features continue to be developed.

**Comment by samccone** [comment]
:+1: thanks for the clarification
