### ISSUE TITLE
How to get started with thorax

### ISSUE THREAD

**Issue by rutaihwa** [walmartlabs/thorax#415]
I am having difficulties getting started with Thorax, from Backbone fundamentals it seems great.
I got tried the jsfiddle and looks like a breaze. The problem is when i try to test these codes on my local env, replacing backbone with thorax nothing happens. Even `hello world` does not seem to work.
What am i doing wrong?
![thorax_hello_w](https://cloud.githubusercontent.com/assets/481028/7492924/43834ca8-f405-11e4-9b13-c4876f852bd0.png)

**Comment by zedd45** [comment]
Perhaps try replacing your Thorax (`js/lib/thorax.min.js`) with the minified, CDN version that has all the included dependencies (http://cdnjs.cloudflare.com/ajax/libs/thorax/2.0.0rc6/thorax.js)?

**Comment by rutaihwa** [comment]
Thanks @zedd45 Actually, I made a stupid overlook! the Thorax file is fine, except i did not tell the body to run the view code, I have now wrapped the file under a function and call the function when page loads `<body onload="fooo();" ></body>`.

**Comment by zedd45** [comment]
:+1:
